title: Viktor Melnikov # your name (or website title) here
logo: "/images/viktor.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Data Scientist/Engineer</b>
  <br><br>
A detail-oriented Data Specialist with a solid mathematical background and technical skills. 
Proficient in Power BI with AWS services, with a solid grasp of Python, SQL and R for comprehensive data analysis and visualization. 
Highly skilled in Machine Learning and Deep Learning, versed in Numpy, Pandas, Sklearn, and TensorFlow, and a familiarity with GitHub for version control. 
  <br><br>
  With 6 years experience in teaching Mathematics which includes 4 years in managing educational teams.<br>
  <a href="www.linkedin.com/in/viktormelnikov">LinkedIn Profile</a> 
  <br>
  <strong> Languages: </strong>
  English -  Advanced knowledge (C1) <br> 
  French – Conversational (B1)<br>
  Dutch – Understanding (A2)<br>
  Ukrainian - Native<br>
  Russian - Native<br>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
