title: Viktor Melnikov # your name (or website title) here
logo: "/images/viktor.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Machine Learning and Data Science Trainee
  <br><br>
  A highly organised person with a solid mathematical background and technical skills. Followed 6 months program "Intelligence Artificielle" taught in French, and in the procces of MITx micro-Masters "Statistics and Data Science" (in English).
  <br><br>
  With 6 years experience in teaching Mathematics which includes 4 years in managing educational teams.<br>
  <a href="www.linkedin.com/in/viktormelnikov">LinkedIn Profile</a> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
