title: Viktor Melnikov # your name (or website title) here
logo: "/images/viktor.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Machine Learning and Python Trainee
  <br><br>
  Proficient in Python, ML techniques, and Deep Learning
  Strong foundation in Pandas, Matplotlib, Seaborn, SciKit-learn, Tensor-Flow Keras
  <br><br>
  Curious and diligent learner 
  <br><br>
  English and French, basic Dutch
  <br><br>
  <a href="www.linkedin.com/in/viktormelnikov">LinkedIn Profile</a> 
  

